apiVersion: v1
kind: Service
metadata:
  name: fadmaro-service
  namespace: fadmaro
spec:
  selector:
    app: fadmaro
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005
  type: NodePort