apiVersion: v1
kind: Service
metadata:
  name: fadmaro-service
  namespace: fadmaro
spec:
  selector:
    app: fadmaro
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30005
  type: NodePort